version: "3.9"
services:
  server:
    environment: 
      - GATEWAY
      - PORT
      - LOGGING_SERVER
      - LOGGING_SERVER_PORT
    build: .
    links:
      - redis
    ports:
      - "${PORT}:8080"
  redis:
    image: redis

networks:
  default:
    external:
      name: project_pixel